### ISSUE TITLE
Task: Do a first design of the app (MVP)

### ISSUE THREAD

**Issue by baan20ty** [IMS-Group-7/Mobile#3]
### Definitions of Done

- [x] Defining the screens we need
    - [x] Identify necessary input fields
        - Mowing area input
        - Start/Stop commands 
- [x] Design of the User Experience with some wireframes (at least 1 per screen)
- [x] Defining a Design System to use (Material 3)
- [x] Design of the UI (mid/high fidelity frames)

**Comment by NekoSelena** [comment]
See here what is a MVP if you don't know yet : https://www.gartner.com/en/marketing/glossary/minimum-viable-product-mvp

Summary: A **Minimum Viable Product** is a version of the product that "includes only the minimum capabilities required to be a viable customer solution." In other words, this version of the product is **not the final one**, but the minimum we need for the scope of this sprint, for example.
